import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/utils/font";

export const metadata: Metadata = {
  title: "EventIn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>{children}</body>
    </html>
  );
}
